source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'SwiftKit', :exclusive => true do
    pod "SwiftKit", :path => "../"
    pod "SwiftKit/TestUtils", :path => "../"
    pod "SwiftKit/QuickUtils", :path => "../"
end

target 'Tests', :exclusive => true do
    pod "SwiftKit", :path => "../"
    pod "SwiftKit/QuickUtils", :path => "../"
    
    pod 'Quick', '0.3.1'
    pod 'Nimble', '1.0.0-rc.1'
end
