source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'SwiftKit', :exclusive => true do
    pod "SwiftKit", :path => "../"
    pod "SwiftKit/TestUtils/XCTest", :path => "../"
    pod "SwiftKit/TestUtils/Quick", :path => "../"
end

target 'Tests', :exclusive => true do
    pod "SwiftKit", :path => "../"
    pod "SwiftKit/TestUtils/Quick", :path => "../"
    pod 'performSelector-swift'

    pod 'Quick', '0.3.1'
    pod 'Nimble', '1.0.0-rc.1'
end
